namespace :admin do
  namespace :clean do
    desc 'Interactively delete all files in /tmp'
    task :tmp do
      Dir['/tmp/*'].each do |f|
        next unless File.file?(f)

        print "Delete #{f}? "
        answer = $stdin.gets
        case answer
        when /^y/
          File.unlink(f)
        when /^q/
          break
        end
      end
    end
    desc 'Prints test task'
    task :test do
      puts 'Test Task'
    end
  end
end
